from django.shortcuts import render

# Create your views here.
def table(request):
  
  return render(request,'index.html',context)
employee = [
    {'Ename':'Anjani',
     'EMPId':1234,
     'Phone_no':9875632571,
     'Role':'Python Developer',
     'Location':'Hyderabad',
     'Salary':700000,
     'DeptNo':'D1',
     'Hiredate':'21-AUG-2025',
     'MGRID':'M1',
     'Shift':'General',
     'PersonalMailId':'srianjani@gmail.com',
     'Gender':'Female',
     'OfficialMailId':'srianjani@office.in',
     'Experience':'6 Months',

     },
    {
    'Ename': 'Rahul',
    'EMPId': 5678,
    'Phone_no': 9876543210,
    'Role': 'Frontend Developer',
    'Location': 'Bangalore',
    'Salary': 850000,
    'DeptNo': 'D2',
    'Hiredate': '15-JUL-2024',
    'MGRID': 'M2',
    'Shift': 'Evening',
    'PersonalMailId': 'rahul.dev@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rahul@office.in',
    'Experience': '1 Year'
},
{
'Ename': 'Isaac',
    'EMPId': 1235,
    'Phone_no': 3432249146,
    'Role': 'Backend Developer',
    'Location': 'Mumbai',
    'Salary': 429653,
    'DeptNo': 'D5',
    'Hiredate': '12-NOV-2022',
    'MGRID': 'M4',
    'Shift': 'Night',
    'PersonalMailId': 'jacksoncarolyn@mcdaniel-brown.com',
    'Gender': 'Male',
    'OfficialMailId': 'isaac@office.in',
    'Experience': '3 Years'
    },
    {
    'Ename': 'Bradley',
    'EMPId': 1236,
    'Phone_no': 3755725454,
    'Role': 'UI/UX Designer',
    'Location': 'Noida',
    'Salary': 762696,
    'DeptNo': 'D5',
    'Hiredate': '28-APR-2025',
    'MGRID': 'M3',
    'Shift': 'General',
    'PersonalMailId': 'jclark@woodard.com',
    'Gender': 'Male',
    'OfficialMailId': 'bradley@office.in',
    'Experience': '3 Years'
  },
   {
    'Ename': 'Elizabeth',
    'EMPId': 1237,
    'Phone_no': 1181485548,
    'Role': 'Data Analyst',
    'Location': 'Noida',
    'Salary': 615832,
    'DeptNo': 'D1',
    'Hiredate': '24-MAY-2023',
    'MGRID': 'M2',
    'Shift': 'Evening',
    'PersonalMailId': 'nfrank@yahoo.com',
    'Gender': 'Female',
    'OfficialMailId': 'elizabeth@office.in',
    'Experience': '6 Months'
  },
  {
    'Ename': 'Marc',
    'EMPId': 1333,
    'Phone_no': 4250372850,
    'Role': 'DevOps Engineer',
    'Location': 'Mumbai',
    'Salary': 905804,
    'DeptNo': 'D2',
    'Hiredate': '11-OCT-2022',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'xcastillo@hotmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'marc@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Benjamin',
    'EMPId': 1334,
    'Phone_no': 2302157649,
    'Role': 'Backend Developer',
    'Location': 'Hyderabad',
    'Salary': 1364966,
    'DeptNo': 'D5',
    'Hiredate': '22-DEC-2022',
    'MGRID': 'M3',
    'Shift': 'Morning',
    'PersonalMailId': 'bpeterson@reed.biz',
    'Gender': 'Male',
    'OfficialMailId': 'benjamin@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Melissa',
    'EMPId': 1335,
    'Phone_no': 9979968173,
    'Role': 'Frontend Developer',
    'Location': 'Pune',
    'Salary': 1240568,
    'DeptNo': 'D1',
    'Hiredate': '15-MAY-2023',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'christinecampbell@bryant.com',
    'Gender': 'Female',
    'OfficialMailId': 'melissa@office.in',
    'Experience': '5 Years'
  },
  {
    'Ename': 'Seth',
    'EMPId': 1336,
    'Phone_no': 3130487895,
    'Role': 'Machine Learning Engineer',
    'Location': 'Hyderabad',
    'Salary': 1231256,
    'DeptNo': 'D4',
    'Hiredate': '21-JUL-2023',
    'MGRID': 'M4',
    'Shift': 'Night',
    'PersonalMailId': 'joneskristen@hotmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'seth@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Chelsey',
    'EMPId': 1337,
    'Phone_no': 3553356850,
    'Role': 'Backend Developer',
    'Location': 'Kolkata',
    'Salary': 1121327,
    'DeptNo': 'D4',
    'Hiredate': '29-JUL-2022',
    'MGRID': 'M1',
    'Shift': 'Evening',
    'PersonalMailId': 'juliewalters@hotmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'chelsey@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Terry',
    'EMPId': 1338,
    'Phone_no': 2496230042,
    'Role': 'Data Analyst',
    'Location': 'Mumbai',
    'Salary': 653186,
    'DeptNo': 'D5',
    'Hiredate': '24-NOV-2023',
    'MGRID': 'M4',
    'Shift': 'Night',
    'PersonalMailId': 'pallen@hotmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'terry@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Adam',
    'EMPId': 1339,
    'Phone_no': 6404738651,
    'Role': 'Frontend Developer',
    'Location': 'Chennai',
    'Salary': 509374,
    'DeptNo': 'D5',
    'Hiredate': '09-FEB-2023',
    'MGRID': 'M2',
    'Shift': 'Morning',
    'PersonalMailId': 'cesarbarr@yahoo.com',
    'Gender': 'Male',
    'OfficialMailId': 'adam@office.in',
    'Experience': '5 Years'
  },
  {
    'Ename': 'Michelle',
    'EMPId': 1340,
    'Phone_no': 3149680649,
    'Role': 'Business Analyst',
    'Location': 'Noida',
    'Salary': 460978,
    'DeptNo': 'D4',
    'Hiredate': '02-DEC-2024',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'scottwilson@hotmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'michelle@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Margaret',
    'EMPId': 1341,
    'Phone_no': 6825280172,
    'Role': 'UI/UX Designer',
    'Location': 'Bangalore',
    'Salary': 777638,
    'DeptNo': 'D3',
    'Hiredate': '04-OCT-2022',
    'MGRID': 'M3',
    'Shift': 'Night',
    'PersonalMailId': 'jwilliams@yahoo.com',
    'Gender': 'Female',
    'OfficialMailId': 'margaret@office.in',
    'Experience': '6 Months'
  },
  {
    'Ename': 'Kyle',
    'EMPId': 1342,
    'Phone_no': 4866315780,
    'Role': 'Backend Developer',
    'Location': 'Delhi',
    'Salary': 997607,
    'DeptNo': 'D1',
    'Hiredate': '22-MAY-2025',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'robert51@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'kyle@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Diana',
    'EMPId': 1343,
    'Phone_no': 9123456781,
    'Role': 'Project Manager',
    'Location': 'Chennai',
    'Salary': 1280000,
    'DeptNo': 'D3',
    'Hiredate': '18-JAN-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'diana.p@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'diana@office.in',
    'Experience': '5 Years'
  },
  {
    'Ename': 'Arjun',
    'EMPId': 1344,
    'Phone_no': 9876504321,
    'Role': 'Python Developer',
    'Location': 'Bangalore',
    'Salary': 890000,
    'DeptNo': 'D1',
    'Hiredate': '11-JUL-2024',
    'MGRID': 'M1',
    'Shift': 'Evening',
    'PersonalMailId': 'arjun.dev@hotmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'arjun@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Priya',
    'EMPId': 1345,
    'Phone_no': 9012345678,
    'Role': 'QA Engineer',
    'Location': 'Hyderabad',
    'Salary': 720000,
    'DeptNo': 'D4',
    'Hiredate': '03-MAR-2022',
    'MGRID': 'M3',
    'Shift': 'Morning',
    'PersonalMailId': 'priya.qa@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'priya@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Ravi',
    'EMPId': 1346,
    'Phone_no': 9234567890,
    'Role': 'DevOps Engineer',
    'Location': 'Pune',
    'Salary': 1100000,
    'DeptNo': 'D2',
    'Hiredate': '27-SEP-2023',
    'MGRID': 'M4',
    'Shift': 'Night',
    'PersonalMailId': 'ravi.devops@yahoo.com',
    'Gender': 'Male',
    'OfficialMailId': 'ravi@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Sneha',
    'EMPId': 1347,
    'Phone_no': 9988776655,
    'Role': 'UI/UX Designer',
    'Location': 'Delhi',
    'Salary': 680000,
    'DeptNo': 'D5',
    'Hiredate': '14-AUG-2024',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'sneha.design@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'sneha@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Nikhil',
    'EMPId': 1348,
    'Phone_no': 9345671230,
    'Role': 'Machine Learning Engineer',
    'Location': 'Noida',
    'Salary': 1250000,
    'DeptNo': 'D4',
    'Hiredate': '10-DEC-2023',
    'MGRID': 'M2',
    'Shift': 'Morning',
    'PersonalMailId': 'nikhil.ml@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'nikhil@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Ayesha',
    'EMPId': 1349,
    'Phone_no': 9876543120,
    'Role': 'Data Analyst',
    'Location': 'Hyderabad',
    'Salary': 810000,
    'DeptNo': 'D1',
    'Hiredate': '05-JUN-2024',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'ayesha.data@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'ayesha@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Vikram',
    'EMPId': 1350,
    'Phone_no': 9123459876,
    'Role': 'Backend Developer',
    'Location': 'Mumbai',
    'Salary': 945000,
    'DeptNo': 'D3',
    'Hiredate': '30-JUL-2022',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'vikram.dev@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'vikram@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Neha',
    'EMPId': 1351,
    'Phone_no': 9988011223,
    'Role': 'Frontend Developer',
    'Location': 'Bangalore',
    'Salary': 860000,
    'DeptNo': 'D2',
    'Hiredate': '11-SEP-2023',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'neha.frontend@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'neha@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Rohit',
    'EMPId': 1352,
    'Phone_no': 9765432109,
    'Role': 'QA Engineer',
    'Location': 'Pune',
    'Salary': 730000,
    'DeptNo': 'D5',
    'Hiredate': '17-MAY-2024',
    'MGRID': 'M3',
    'Shift': 'Night',
    'PersonalMailId': 'rohit.qa@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rohit@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Kavya',
    'EMPId': 1353,
    'Phone_no': 9012987654,
    'Role': 'Business Analyst',
    'Location': 'Delhi',
    'Salary': 940000,
    'DeptNo': 'D2',
    'Hiredate': '07-MAR-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'kavya.ba@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'kavya@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Siddharth',
    'EMPId': 1354,
    'Phone_no': 9087654321,
    'Role': 'DevOps Engineer',
    'Location': 'Hyderabad',
    'Salary': 1150000,
    'DeptNo': 'D3',
    'Hiredate': '19-DEC-2022',
    'MGRID': 'M1',
    'Shift': 'Evening',
    'PersonalMailId': 'sid.devops@yahoo.com',
    'Gender': 'Male',
    'OfficialMailId': 'siddharth@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Meera',
    'EMPId': 1355,
    'Phone_no': 9021345678,
    'Role': 'Python Developer',
    'Location': 'Pune',
    'Salary': 870000,
    'DeptNo': 'D1',
    'Hiredate': '22-AUG-2024',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'meera.python@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'meera@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Rahul',
    'EMPId': 1356,
    'Phone_no': 9988123456,
    'Role': 'UI/UX Designer',
    'Location': 'Mumbai',
    'Salary': 690000,
    'DeptNo': 'D4',
    'Hiredate': '16-JUN-2023',
    'MGRID': 'M3',
    'Shift': 'Night',
    'PersonalMailId': 'rahul.design@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rahul@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Swati',
    'EMPId': 1357,
    'Phone_no': 9090987654,
    'Role': 'Data Analyst',
    'Location': 'Noida',
    'Salary': 810000,
    'DeptNo': 'D5',
    'Hiredate': '25-JAN-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'swati.data@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'swati@office.in',
    'Experience': '1 Year'
  },
   {
    'Ename': 'Ankit',
    'EMPId': 1358,
    'Phone_no': 9012123456,
    'Role': 'Software Tester',
    'Location': 'Hyderabad',
    'Salary': 720000,
    'DeptNo': 'D4',
    'Hiredate': '03-APR-2024',
    'MGRID': 'M3',
    'Shift': 'Morning',
    'PersonalMailId': 'ankit.tester@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'ankit@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Divya',
    'EMPId': 1359,
    'Phone_no': 9923456781,
    'Role': 'Python Developer',
    'Location': 'Bangalore',
    'Salary': 890000,
    'DeptNo': 'D1',
    'Hiredate': '17-JUL-2022',
    'MGRID': 'M1',
    'Shift': 'Evening',
    'PersonalMailId': 'divya.dev@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'divya@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Farhan',
    'EMPId': 1360,
    'Phone_no': 9345011223,
    'Role': 'Database Administrator',
    'Location': 'Chennai',
    'Salary': 1020000,
    'DeptNo': 'D2',
    'Hiredate': '29-NOV-2023',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'farhan.db@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'farhan@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Lavanya',
    'EMPId': 1361,
    'Phone_no': 9876012345,
    'Role': 'Business Analyst',
    'Location': 'Delhi',
    'Salary': 950000,
    'DeptNo': 'D5',
    'Hiredate': '21-MAR-2023',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'lavanya.ba@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'lavanya@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Harsha',
    'EMPId': 1362,
    'Phone_no': 9100123456,
    'Role': 'Frontend Developer',
    'Location': 'Pune',
    'Salary': 870000,
    'DeptNo': 'D3',
    'Hiredate': '06-JUN-2022',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'harsha.front@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'harsha@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Snehal',
    'EMPId': 1363,
    'Phone_no': 9876001122,
    'Role': 'Cloud Engineer',
    'Location': 'Mumbai',
    'Salary': 1090000,
    'DeptNo': 'D2',
    'Hiredate': '12-FEB-2024',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'snehal.cloud@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'snehal@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Tarun',
    'EMPId': 1364,
    'Phone_no': 9021123456,
    'Role': 'Full Stack Developer',
    'Location': 'Hyderabad',
    'Salary': 980000,
    'DeptNo': 'D1',
    'Hiredate': '09-JAN-2023',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'tarun.fsdev@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'tarun@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Pooja',
    'EMPId': 1365,
    'Phone_no': 9988772211,
    'Role': 'Data Engineer',
    'Location': 'Noida',
    'Salary': 1120000,
    'DeptNo': 'D4',
    'Hiredate': '05-MAY-2022',
    'MGRID': 'M3',
    'Shift': 'Night',
    'PersonalMailId': 'pooja.data@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'pooja@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Manoj',
    'EMPId': 1366,
    'Phone_no': 9012456789,
    'Role': 'Java Developer',
    'Location': 'Chennai',
    'Salary': 920000,
    'DeptNo': 'D3',
    'Hiredate': '20-SEP-2024',
    'MGRID': 'M4',
    'Shift': 'Evening',
    'PersonalMailId': 'manoj.java@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'manoj@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Anusha',
    'EMPId': 1367,
    'Phone_no': 9876098765,
    'Role': 'Technical Writer',
    'Location': 'Delhi',
    'Salary': 780000,
    'DeptNo': 'D5',
    'Hiredate': '27-JUL-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'anusha.writer@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'anusha@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Rajesh',
    'EMPId': 1368,
    'Phone_no': 9090909090,
    'Role': 'System Administrator',
    'Location': 'Pune',
    'Salary': 850000,
    'DeptNo': 'D3',
    'Hiredate': '08-MAY-2022',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'rajesh.sys@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rajesh@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Ishita',
    'EMPId': 1369,
    'Phone_no': 9876540011,
    'Role': 'Product Manager',
    'Location': 'Bangalore',
    'Salary': 1450000,
    'DeptNo': 'D2',
    'Hiredate': '13-NOV-2023',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'ishita.pm@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'ishita@office.in',
    'Experience': '5 Years'
  },
  {
    'Ename': 'Gaurav',
    'EMPId': 1370,
    'Phone_no': 9000001122,
    'Role': 'AI Engineer',
    'Location': 'Hyderabad',
    'Salary': 1350000,
    'DeptNo': 'D1',
    'Hiredate': '24-FEB-2024',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'gaurav.ai@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'gaurav@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Neelima',
    'EMPId': 1371,
    'Phone_no': 9988991122,
    'Role': 'Scrum Master',
    'Location': 'Noida',
    'Salary': 1280000,
    'DeptNo': 'D5',
    'Hiredate': '01-AUG-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'neelima.scrum@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'neelima@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Kiran',
    'EMPId': 1372,
    'Phone_no': 9123456000,
    'Role': 'Security Analyst',
    'Location': 'Chennai',
    'Salary': 960000,
    'DeptNo': 'D4',
    'Hiredate': '19-JAN-2023',
    'MGRID': 'M1',
    'Shift': 'Night',
    'PersonalMailId': 'kiran.security@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'kiran@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Shruti',
    'EMPId': 1373,
    'Phone_no': 9988001122,
    'Role': 'Mobile App Developer',
    'Location': 'Hyderabad',
    'Salary': 970000,
    'DeptNo': 'D2',
    'Hiredate': '14-MAR-2024',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'shruti.appdev@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'shruti@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Yash',
    'EMPId': 1374,
    'Phone_no': 9123012345,
    'Role': 'AI Researcher',
    'Location': 'Bangalore',
    'Salary': 1550000,
    'DeptNo': 'D1',
    'Hiredate': '22-DEC-2023',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'yash.ai@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'yash@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Simran',
    'EMPId': 1375,
    'Phone_no': 9900112233,
    'Role': 'UX Researcher',
    'Location': 'Delhi',
    'Salary': 880000,
    'DeptNo': 'D3',
    'Hiredate': '10-JUN-2022',
    'MGRID': 'M2',
    'Shift': 'Evening',
    'PersonalMailId': 'simran.ux@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'simran@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Aditya',
    'EMPId': 1376,
    'Phone_no': 9876512345,
    'Role': 'Blockchain Developer',
    'Location': 'Mumbai',
    'Salary': 1380000,
    'DeptNo': 'D4',
    'Hiredate': '03-OCT-2023',
    'MGRID': 'M3',
    'Shift': 'Night',
    'PersonalMailId': 'aditya.block@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'aditya@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Nisha',
    'EMPId': 1377,
    'Phone_no': 9090901212,
    'Role': 'Content Strategist',
    'Location': 'Pune',
    'Salary': 760000,
    'DeptNo': 'D5',
    'Hiredate': '26-JAN-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'nisha.content@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'nisha@office.in',
    'Experience': '1 Year'
  },
  {
    'Ename': 'Ritika',
    'EMPId': 1378,
    'Phone_no': 9876007788,
    'Role': 'DevOps Engineer',
    'Location': 'Bangalore',
    'Salary': 1120000,
    'DeptNo': 'D2',
    'Hiredate': '15-AUG-2023',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'ritika.devops@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'ritika@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Sagar',
    'EMPId': 1379,
    'Phone_no': 9000112233,
    'Role': 'Backend Developer',
    'Location': 'Hyderabad',
    'Salary': 980000,
    'DeptNo': 'D1',
    'Hiredate': '11-SEP-2022',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'sagar.backend@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'sagar@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Pallavi',
    'EMPId': 1380,
    'Phone_no': 9988223344,
    'Role': 'QA Engineer',
    'Location': 'Noida',
    'Salary': 860000,
    'DeptNo': 'D4',
    'Hiredate': '28-MAY-2023',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'pallavi.qa@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'pallavi@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Deepak',
    'EMPId': 1381,
    'Phone_no': 9123456781,
    'Role': 'Network Engineer',
    'Location': 'Chennai',
    'Salary': 940000,
    'DeptNo': 'D3',
    'Hiredate': '02-JAN-2024',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'deepak.network@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'deepak@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Kavya',
    'EMPId': 1382,
    'Phone_no': 9090998877,
    'Role': 'HR Executive',
    'Location': 'Pune',
    'Salary': 720000,
    'DeptNo': 'D5',
    'Hiredate': '18-JUN-2022',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'kavya.hr@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'kavya@office.in',
    'Experience': '1.5 Years'
  },
  {
    'Ename': 'Aarav',
    'EMPId': 1383,
    'Phone_no': 9012345678,
    'Role': 'Frontend Developer',
    'Location': 'Delhi',
    'Salary': 910000,
    'DeptNo': 'D1',
    'Hiredate': '07-FEB-2023',
    'MGRID': 'M2',
    'Shift': 'Morning',
    'PersonalMailId': 'aarav.frontend@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'aarav@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Meera',
    'EMPId': 1384,
    'Phone_no': 9887766554,
    'Role': 'Business Analyst',
    'Location': 'Mumbai',
    'Salary': 1050000,
    'DeptNo': 'D3',
    'Hiredate': '12-APR-2022',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'meera.ba@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'meera@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Rohit',
    'EMPId': 1385,
    'Phone_no': 9876543210,
    'Role': 'Machine Learning Engineer',
    'Location': 'Hyderabad',
    'Salary': 1320000,
    'DeptNo': 'D2',
    'Hiredate': '29-DEC-2023',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'rohit.ml@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rohit@office.in',
    'Experience': '3.5 Years'
  },
  {
    'Ename': 'Divya',
    'EMPId': 1386,
    'Phone_no': 9900990011,
    'Role': 'Technical Recruiter',
    'Location': 'Bangalore',
    'Salary': 780000,
    'DeptNo': 'D5',
    'Hiredate': '06-JUL-2021',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'divya.recruit@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'divya@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Nikhil',
    'EMPId': 1387,
    'Phone_no': 9111223344,
    'Role': 'Database Administrator',
    'Location': 'Chennai',
    'Salary': 970000,
    'DeptNo': 'D4',
    'Hiredate': '16-MAY-2023',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'nikhil.db@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'nikhil@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Tanvi',
    'EMPId': 1388,
    'Phone_no': 9090909091,
    'Role': 'Cloud Engineer',
    'Location': 'Hyderabad',
    'Salary': 1150000,
    'DeptNo': 'D2',
    'Hiredate': '22-AUG-2022',
    'MGRID': 'M3',
    'Shift': 'Morning',
    'PersonalMailId': 'tanvi.cloud@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'tanvi@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Ramesh',
    'EMPId': 1389,
    'Phone_no': 9888877777,
    'Role': 'Support Engineer',
    'Location': 'Chennai',
    'Salary': 740000,
    'DeptNo': 'D5',
    'Hiredate': '10-NOV-2023',
    'MGRID': 'M1',
    'Shift': 'Night',
    'PersonalMailId': 'ramesh.support@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'ramesh@office.in',
    'Experience': '1.5 Years'
  },
  {
    'Ename': 'Ankita',
    'EMPId': 1390,
    'Phone_no': 9123123456,
    'Role': 'SEO Specialist',
    'Location': 'Delhi',
    'Salary': 690000,
    'DeptNo': 'D4',
    'Hiredate': '30-JAN-2023',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'ankita.seo@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'ankita@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Siddharth',
    'EMPId': 1391,
    'Phone_no': 9098765432,
    'Role': 'Software Tester',
    'Location': 'Pune',
    'Salary': 830000,
    'DeptNo': 'D1',
    'Hiredate': '18-MAR-2022',
    'MGRID': 'M2',
    'Shift': 'Evening',
    'PersonalMailId': 'siddharth.test@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'siddharth@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Harshita',
    'EMPId': 1392,
    'Phone_no': 9988776655,
    'Role': 'UI/UX Designer',
    'Location': 'Bangalore',
    'Salary': 1010000,
    'DeptNo': 'D3',
    'Hiredate': '25-APR-2023',
    'MGRID': 'M3',
    'Shift': 'General',
    'PersonalMailId': 'harshita.uiux@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'harshita@office.in',
    'Experience': '3 Years'
  },
   {
    'Ename': 'Shalini',
    'EMPId': 1398,
    'Phone_no': 9123987654,
    'Role': 'Scrum Master',
    'Location': 'Pune',
    'Salary': 1125000,
    'DeptNo': 'D3',
    'Hiredate': '20-MAY-2022',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'shalini.scrum@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'shalini@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Yogesh',
    'EMPId': 1399,
    'Phone_no': 9012341199,
    'Role': 'Mobile App Developer',
    'Location': 'Delhi',
    'Salary': 980000,
    'DeptNo': 'D1',
    'Hiredate': '08-AUG-2023',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'yogesh.mobiledev@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'yogesh@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Reema',
    'EMPId': 1400,
    'Phone_no': 9988992211,
    'Role': 'Content Strategist',
    'Location': 'Hyderabad',
    'Salary': 820000,
    'DeptNo': 'D5',
    'Hiredate': '25-SEP-2022',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'reema.content@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'reema@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Amit',
    'EMPId': 1401,
    'Phone_no': 9876076543,
    'Role': 'IT Support Specialist',
    'Location': 'Mumbai',
    'Salary': 750000,
    'DeptNo': 'D4',
    'Hiredate': '14-JAN-2024',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'amit.itsupport@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'amit@office.in',
    'Experience': '1.5 Years'
  },
  {
    'Ename': 'Sneha',
    'EMPId': 1402,
    'Phone_no': 9123455566,
    'Role': 'Technical Writer',
    'Location': 'Chennai',
    'Salary': 680000,
    'DeptNo': 'D2',
    'Hiredate': '03-APR-2023',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'sneha.writer@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'sneha@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Vikram',
    'EMPId': 1403,
    'Phone_no': 9111233445,
    'Role': 'AI Engineer',
    'Location': 'Bangalore',
    'Salary': 1450000,
    'DeptNo': 'D2',
    'Hiredate': '15-MAY-2023',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'vikram.ai@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'vikram@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Preeti',
    'EMPId': 1404,
    'Phone_no': 9877665543,
    'Role': 'DevOps Engineer',
    'Location': 'Hyderabad',
    'Salary': 1280000,
    'DeptNo': 'D1',
    'Hiredate': '27-MAR-2022',
    'MGRID': 'M2',
    'Shift': 'Evening',
    'PersonalMailId': 'preeti.devops@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'preeti@office.in',
    'Experience': '3.5 Years'
  },
  {
    'Ename': 'Ravi',
    'EMPId': 1405,
    'Phone_no': 9898123456,
    'Role': 'Full Stack Developer',
    'Location': 'Delhi',
    'Salary': 1320000,
    'DeptNo': 'D3',
    'Hiredate': '12-DEC-2023',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'ravi.fullstack@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'ravi@office.in',
    'Experience': '4.5 Years'
  },
  {
    'Ename': 'Kavya',
    'EMPId': 1406,
    'Phone_no': 9966554433,
    'Role': 'Data Analyst',
    'Location': 'Chennai',
    'Salary': 940000,
    'DeptNo': 'D4',
    'Hiredate': '09-FEB-2023',
    'MGRID': 'M3',
    'Shift': 'Morning',
    'PersonalMailId': 'kavya.analyst@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'kavya@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Naveen',
    'EMPId': 1407,
    'Phone_no': 9100223344,
    'Role': 'Network Engineer',
    'Location': 'Pune',
    'Salary': 890000,
    'DeptNo': 'D5',
    'Hiredate': '05-OCT-2022',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'naveen.network@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'naveen@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Divya',
    'EMPId': 1408,
    'Phone_no': 9876543212,
    'Role': 'Machine Learning Engineer',
    'Location': 'Bangalore',
    'Salary': 1380000,
    'DeptNo': 'D2',
    'Hiredate': '17-JUN-2023',
    'MGRID': 'M4',
    'Shift': 'General',
    'PersonalMailId': 'divya.ml@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'divya@office.in',
    'Experience': '3.5 Years'
  },
  {
    'Ename': 'Suresh',
    'EMPId': 1409,
    'Phone_no': 9888123412,
    'Role': 'Cloud Architect',
    'Location': 'Hyderabad',
    'Salary': 1600000,
    'DeptNo': 'D1',
    'Hiredate': '29-SEP-2022',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'suresh.cloud@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'suresh@office.in',
    'Experience': '5 Years'
  },
  {
    'Ename': 'Nikita',
    'EMPId': 1410,
    'Phone_no': 9123012345,
    'Role': 'Frontend Developer',
    'Location': 'Chennai',
    'Salary': 960000,
    'DeptNo': 'D3',
    'Hiredate': '08-APR-2023',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'nikita.frontend@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'nikita@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Faizan',
    'EMPId': 1411,
    'Phone_no': 9012347777,
    'Role': 'Back-End Developer',
    'Location': 'Mumbai',
    'Salary': 1020000,
    'DeptNo': 'D4',
    'Hiredate': '15-JUL-2022',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'faizan.backend@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'faizan@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Shruti',
    'EMPId': 1412,
    'Phone_no': 9988771122,
    'Role': 'UI/UX Researcher',
    'Location': 'Pune',
    'Salary': 970000,
    'DeptNo': 'D5',
    'Hiredate': '22-DEC-2023',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'shruti.uiux@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'shruti@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Harshit',
    'EMPId': 1413,
    'Phone_no': 9876501234,
    'Role': 'Blockchain Developer',
    'Location': 'Hyderabad',
    'Salary': 1480000,
    'DeptNo': 'D1',
    'Hiredate': '10-JAN-2024',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'harshit.blockchain@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'harshit@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Megha',
    'EMPId': 1414,
    'Phone_no': 9123456701,
    'Role': 'SEO Analyst',
    'Location': 'Delhi',
    'Salary': 720000,
    'DeptNo': 'D5',
    'Hiredate': '05-AUG-2023',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'megha.seo@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'megha@office.in',
    'Experience': '1.5 Years'
  },
  {
    'Ename': 'Rohit',
    'EMPId': 1415,
    'Phone_no': 9988012345,
    'Role': 'Tech Lead',
    'Location': 'Bangalore',
    'Salary': 1800000,
    'DeptNo': 'D3',
    'Hiredate': '20-FEB-2022',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'rohit.techlead@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rohit@office.in',
    'Experience': '6 Years'
  },
  {
    'Ename': 'Pooja',
    'EMPId': 1416,
    'Phone_no': 9876701234,
    'Role': 'Business Analyst',
    'Location': 'Pune',
    'Salary': 1050000,
    'DeptNo': 'D2',
    'Hiredate': '14-MAR-2023',
    'MGRID': 'M3',
    'Shift': 'General',
    'PersonalMailId': 'pooja.ba@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'pooja@office.in',
    'Experience': '3.5 Years'
  },
  {
    'Ename': 'Siddharth',
    'EMPId': 1417,
    'Phone_no': 9001122334,
    'Role': 'Graphic Designer',
    'Location': 'Chennai',
    'Salary': 820000,
    'DeptNo': 'D4',
    'Hiredate': '01-NOV-2022',
    'MGRID': 'M2',
    'Shift': 'Evening',
    'PersonalMailId': 'siddharth.design@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'siddharth@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Tanvi',
    'EMPId': 1418,
    'Phone_no': 9876547788,
    'Role': 'Cybersecurity Analyst',
    'Location': 'Hyderabad',
    'Salary': 1180000,
    'DeptNo': 'D2',
    'Hiredate': '12-JUN-2023',
    'MGRID': 'M3',
    'Shift': 'Night',
    'PersonalMailId': 'tanvi.cyber@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'tanvi@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Arjun',
    'EMPId': 1419,
    'Phone_no': 9012334567,
    'Role': 'Technical Architect',
    'Location': 'Bangalore',
    'Salary': 1650000,
    'DeptNo': 'D1',
    'Hiredate': '18-JAN-2022',
    'MGRID': 'M1',
    'Shift': 'Morning',
    'PersonalMailId': 'arjun.architect@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'arjun@office.in',
    'Experience': '6 Years'
  },
  {
    'Ename': 'Neha',
    'EMPId': 1420,
    'Phone_no': 9988773344,
    'Role': 'QA Engineer',
    'Location': 'Delhi',
    'Salary': 880000,
    'DeptNo': 'D3',
    'Hiredate': '26-MAY-2023',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'neha.qa@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'neha@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Karan',
    'EMPId': 1421,
    'Phone_no': 9123452211,
    'Role': 'Database Administrator',
    'Location': 'Mumbai',
    'Salary': 970000,
    'DeptNo': 'D4',
    'Hiredate': '03-OCT-2022',
    'MGRID': 'M4',
    'Shift': 'Evening',
    'PersonalMailId': 'karan.dba@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'karan@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Aaradhya',
    'EMPId': 1422,
    'Phone_no': 9112233445,
    'Role': 'Data Scientist',
    'Location': 'Chennai',
    'Salary': 1350000,
    'DeptNo': 'D5',
    'Hiredate': '20-APR-2023',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'aaradhya.ds@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'aaradhya@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Ritika',
    'EMPId': 1423,
    'Phone_no': 9876123401,
    'Role': 'HR Manager',
    'Location': 'Delhi',
    'Salary': 1100000,
    'DeptNo': 'D5',
    'Hiredate': '10-MAR-2022',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'ritika.hr@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'ritika@office.in',
    'Experience': '4.5 Years'
  },
  {
    'Ename': 'Manoj',
    'EMPId': 1424,
    'Phone_no': 9012678945,
    'Role': 'System Administrator',
    'Location': 'Hyderabad',
    'Salary': 950000,
    'DeptNo': 'D1',
    'Hiredate': '23-JUN-2023',
    'MGRID': 'M2',
    'Shift': 'Night',
    'PersonalMailId': 'manoj.sysadmin@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'manoj@office.in',
    'Experience': '3.5 Years'
  },
  {
    'Ename': 'Deepika',
    'EMPId': 1425,
    'Phone_no': 9988123467,
    'Role': 'Content Strategist',
    'Location': 'Mumbai',
    'Salary': 790000,
    'DeptNo': 'D3',
    'Hiredate': '14-SEP-2022',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'deepika.content@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'deepika@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Ankit',
    'EMPId': 1426,
    'Phone_no': 9100456123,
    'Role': 'IT Support',
    'Location': 'Chennai',
    'Salary': 620000,
    'DeptNo': 'D4',
    'Hiredate': '01-NOV-2023',
    'MGRID': 'M2',
    'Shift': 'Morning',
    'PersonalMailId': 'ankit.support@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'ankit@office.in',
    'Experience': '1.5 Years'
  },
  {
    'Ename': 'Sneha',
    'EMPId': 1427,
    'Phone_no': 9911223344,
    'Role': 'Marketing Manager',
    'Location': 'Bangalore',
    'Salary': 1250000,
    'DeptNo': 'D2',
    'Hiredate': '19-MAY-2023',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'sneha.marketing@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'sneha@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Rahul',
    'EMPId': 1428,
    'Phone_no': 9876543210,
    'Role': 'DevOps Engineer',
    'Location': 'Pune',
    'Salary': 1150000,
    'DeptNo': 'D1',
    'Hiredate': '05-MAR-2022',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'rahul.devops@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'rahul@office.in',
    'Experience': '4 Years'
  },
  {
    'Ename': 'Ishita',
    'EMPId': 1429,
    'Phone_no': 9123456789,
    'Role': 'Technical Writer',
    'Location': 'Delhi',
    'Salary': 850000,
    'DeptNo': 'D3',
    'Hiredate': '15-AUG-2023',
    'MGRID': 'M4',
    'Shift': 'Morning',
    'PersonalMailId': 'ishita.writer@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'ishita@office.in',
    'Experience': '2 Years'
  },
  {
    'Ename': 'Vikram',
    'EMPId': 1430,
    'Phone_no': 9988776655,
    'Role': 'Network Engineer',
    'Location': 'Bangalore',
    'Salary': 960000,
    'DeptNo': 'D4',
    'Hiredate': '09-JUL-2023',
    'MGRID': 'M3',
    'Shift': 'Evening',
    'PersonalMailId': 'vikram.network@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'vikram@office.in',
    'Experience': '2.5 Years'
  },
  {
    'Ename': 'Preeti',
    'EMPId': 1431,
    'Phone_no': 9876001234,
    'Role': 'AI Researcher',
    'Location': 'Hyderabad',
    'Salary': 1450000,
    'DeptNo': 'D5',
    'Hiredate': '12-APR-2024',
    'MGRID': 'M1',
    'Shift': 'General',
    'PersonalMailId': 'preeti.ai@gmail.com',
    'Gender': 'Female',
    'OfficialMailId': 'preeti@office.in',
    'Experience': '3 Years'
  },
  {
    'Ename': 'Sanjay',
    'EMPId': 1432,
    'Phone_no': 9001234567,
    'Role': 'Scrum Master',
    'Location': 'Mumbai',
    'Salary': 1280000,
    'DeptNo': 'D2',
    'Hiredate': '28-FEB-2022',
    'MGRID': 'M2',
    'Shift': 'General',
    'PersonalMailId': 'sanjay.scrum@gmail.com',
    'Gender': 'Male',
    'OfficialMailId': 'sanjay@office.in',
    'Experience': '4.5 Years'
  },

  ]
context = {
    'data':employee
  }

# cards view
def cards(request):
  return render(request,'cards.html')